info.build.description: ${project.description}
info.build.name: ${project.name}
info.build.version: ${project.version}
server.port: 5050

spring.data.elasticsearch.cluster-nodes: 127.0.0.1:9200
webdriver.chrome.driver: /path/to/chromedriver
delayBetweenRequests: true

amazonAccesskey: 
amazonSecret: 
amazonTag: 